name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip && pip install -r requirements.txt
    # - name: setup variable evironment
    #  env:
    #    SECRET: ${{ secrets.TESTING }}
    - name: Test with pytest
      run: |
        pytest
